### ISSUE TITLE
湖南电信IPTV源使用VLC播放黑屏，但能收到组播包

### ISSUE THREAD

**Issue by t0nyt4ng** [imDazui/Tvlist-awesome-m3u-m3u8#11]
湖南IPTV源使用VLC播放黑屏，但能收到组播包
![image](https://user-images.githubusercontent.com/8139781/76677978-dfe31d00-660e-11ea-9f4f-12c3f9de934f.png)
![image](https://user-images.githubusercontent.com/8139781/76677984-e8d3ee80-660e-11ea-9e49-ebde2489d742.png)
![image](https://user-images.githubusercontent.com/8139781/76677995-eec9cf80-660e-11ea-9d83-e02a5cf47587.png)

**Comment by holywen** [comment]
根本打不开，ping这个服务器也ping不到。

**Comment by imDazui** [comment]
拨不出是收录地址失效问题
