### ISSUE TITLE
台湾香港海外202005.m3u8 日本部分直播源名称错误,同时在同服务器上抓到了其他源

### ISSUE THREAD

**Issue by TeddyKagurazaka** [imDazui/Tvlist-awesome-m3u-m3u8#17]
203.162.235.41下(以下是端口号)

16901 : NHK Eテレ -> NHK World Premium (https://nhkworldpremium.com/schedules)
16911 : BSフジ -> WOWOW シネマ
16916 : WOWOW シネマ -> WOWOW プライム
\+ 16917 : BBC World News
\+ 16918 : CNN
\+ 16919 : CNBC
\+ 16924 : Golf Network

**Comment by imDazui** [comment]
感谢
