### ISSUE TITLE
贡献一个EPG采集网站

### ISSUE THREAD

**Issue by alexliyu7352** [imDazui/Tvlist-awesome-m3u-m3u8#18]
我发现你推荐的EPG, 第一个收费的, 剩余的对咱们用处不大, 所以我这里贡献一个

https://epg.pm

大概上面2000来个频道的EPG吧, 
页面下方有一个xmltv的接口, 每天更新一周节目预告.

**Comment by wangweiarr** [comment]
> 我发现你推荐的EPG, 第一个收费的, 剩余的对咱们用处不大, 所以我这里贡献一个
> 
> https://epg.pm
> 
> 大概上面2000来个频道的EPG吧,
> 页面下方有一个xmltv的接口, 每天更新一周节目预告.

下方xmltv接口是怎么用的？电脑打不开，普通app有没有填写xml链接的地方。

**Comment by maxiaowei1016** [comment]
收到，谢谢

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by imDazui** [comment]
配合科学上网选择会很多
