### ISSUE TITLE
请教下直播源在电脑上用potplayer播放不卡，但是在电视盒子中就卡

### ISSUE THREAD

**Issue by zhizunbao84** [imDazui/Tvlist-awesome-m3u-m3u8#21]
直播源我都用网络检测工具检测过，留下的都是网络环境畅通的（显示是绿色）
同样的网络环境，在电脑上用potplayer播放不卡，甚至我装的kodi播放也不卡
但是在天猫魔盒2中用kodi或者mxplayer播放就会卡。
请教下大家这是什么原因呢？

**Comment by zhizunbao84** [comment]
求解！！

**Comment by aug7** [comment]
cpu性能不够

**Comment by six220mao** [comment]
电视盒子配置太低了

**Comment by StephenGiant** [comment]
盒子估计是软解了吧 卡很正常

**Comment by imDazui** [comment]
请放弃安卓盒子
