### ISSUE TITLE
1300个直播源全部有效【全部4k老电脑别用】.m3u8 这个无法播放

### ISSUE THREAD

**Issue by longwang1995** [imDazui/Tvlist-awesome-m3u-m3u8#29]
![image](https://user-images.githubusercontent.com/33283123/154080891-5c9c23fe-bc7b-4eae-9141-aaa5f5fb9433.png)

本人网络是广东移动的

**Comment by pifeifei** [comment]
我也试了不行，不知道是不是我操作不对，用 vlc 和 iina 都不行

**Comment by M3Ulica** [comment]
Okay
Link or m3u for trial

**Comment by imDazui** [comment]
文件指向地址实效性问题。
