### ISSUE TITLE
安卓客户端推荐

### ISSUE THREAD

**Issue by luvzhaojing** [imDazui/Tvlist-awesome-m3u-m3u8#3]
在谷歌商店有个IPTV挺好用的，这里是专业破解版http://yx.bsh.me/29742.html
还有个ott navigator也不错，但是操作略微复杂
http://epg.51zmt.top:8000
这个网站有中文EPG，建议链接，并且最好在你的电视列表里对照他的EPG频道里修改频道名称，频道名称修改成他的那个表里的tvg-name，这样直播源的频道就会匹配到EPG，否则无法识别到，配合我上面推荐的安卓客户端，非常好用

**Comment by shiburuna** [comment]
http://epg.51zmt.top:8000这个网站有中文EPG，建议链接，并且最好在你的电视列表里对照他的EPG频道里修改频道名称，频道名称修改成他的那个表里的tvg-name，这样直播源的频道就会匹配到EPG，否则无法识别到，配合我上面推荐的安卓客户端，非常好用

**Comment by Roger8** [comment]
http://yx.bsh.me/29742.html 页面打不开
