### ISSUE TITLE
求一个世界杯的直播源

### ISSUE THREAD

**Issue by axhiao** [imDazui/Tvlist-awesome-m3u-m3u8#40]
找了很多直播源都不可用，有大佬更新一个世界杯的直播源吗，多谢！

**Comment by imDazui** [comment]
需要代理∶
https://raw.githubusercontent.com/youshandefeiyang/IPTV/main/main/IPTV.m3u

不需要代理∶ 
https://cdn.jsdelivr.net/gh/youshandefeiyang/IPTV@2.0/main/IPTV.m3u

CCTV16-4K-SDR源：
http://111.20.105.192:6610/000000001000/5000000008000023254/index.m3u8?channel-id=bestzb&Contentid=5000000008000023254&livemode=1&stbId=3

CCTV16-4K-HLG源：
http://27.36.62.163:9090/live/4010.m3u8

**Comment by YanCC506** [comment]
> 
非常感谢！

**Comment by bzzjh** [comment]
也都看不了啊

**Comment by Drogochen** [comment]
谢谢老板

**Comment by dongdzy** [comment]
谢谢🙏

**Comment by ipolm** [comment]
这个github项目的m3u要怎么添加到iptv的

**Comment by lywly** [comment]
`CCTV16`的`IPv6`源太给力了

**Comment by imDazui** [comment]
> `CCTV16`的`IPv6`源太给力了

且用且珍惜，随时失效可能
