### ISSUE TITLE
怎么添加

### ISSUE THREAD

**Issue by ipolm** [imDazui/Tvlist-awesome-m3u-m3u8#44]
项目里提供的m3u是怎么添加到iptv的，是直接复制链接吗，试了不对嘞

**Comment by imDazui** [comment]
https://github.com/imDazui/Tvlist-awesome-m3u-m3u8#%E5%B7%A5%E5%85%B7

试试看这些

**Comment by ipolm** [comment]
> https://github.com/imDazui/Tvlist-awesome-m3u-m3u8#%E5%B7%A5%E5%85%B7
> 
> 试试看这些

我用的是iptvpro这个软件，比如本项目里m3u资源，是不是直接打开，然后再地址栏复制链接添加就可以了呢？比如：https://github.com/imDazui/Tvlist-awesome-m3u-m3u8/blob/master/m3u/1300个直播源全部有效【全部4k老电脑别用】.m3u8 这条，如果这个方法没错，那就是iptv这个软件不行了吗？，我在项目后面推荐的安卓软件都试了，更用不来

**Comment by imDazui** [comment]
名称：Android 电视家3.0电视直播软件 v3.10.16去广告VIP版

描述：电视家app(电视家3.0TV版)是一款智能电视及机顶盒电视直播软件,拥有大量稳定的高清频道,数字频道,经典电影专栏等.电视家3.0电视版,支持直播时移,直播回看预约,高清/超清直播源切换,可自建频道自定义分享码.

链接：https://www.aliyundrive.com/s/Da2B18WRS46
