### ISSUE TITLE
安徽移动的IPTV

### ISSUE THREAD

**Issue by shinyypig** [imDazui/Tvlist-awesome-m3u-m3u8#45]
只能用安徽移动的ip观看，别的ip应该是看不了的，但是很稳。
------------------------------------------------------------
#EXTM3U 
#EXTINF:-1, group-title="CCTV", CCTV-1
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-1/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-2
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-2/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-3
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-cctv3/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-4
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-4/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-5
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-5/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-6
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-cctv6/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-7
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-7/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-8
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-cctv8/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-9
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-news/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-10
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-10/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-11
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-11/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-12
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-12/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-13
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-13/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-14
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-14/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-15
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-15/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-16
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-cctv16/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-17
http://120.210.193.151:8006/120000001002/XMTcctv-17hd/index.m3u8
#EXTINF:-1, group-title="其他", CGTN
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-9/1.m3u8
#EXTINF:-1, group-title="地方卫视", 安徽卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/anhuistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 湖南卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/hunanstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 东方卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/dongfangstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 北京卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/beijingstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 浙江卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/zhejiangstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 江苏卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jiangsustv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 天津卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/tianjinstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 山东卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/shandongstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 辽宁卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-liaoningstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 深圳卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/shenzhenstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 江西卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jiangxistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 贵州卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-guizhoustv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 吉林卫视
http://120.210.193.151:8006/120000001002/XMTjlwshd/index.m3u8
#EXTINF:-1, group-title="地方卫视", 广东卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/guangdongstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 湖北卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-hubeistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 河北卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-hebeistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 山西卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/shanxistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 重庆卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/chongqingstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 四川卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-sichuanstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 广西卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/guangxistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 陕西卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/shanxi1stv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 甘肃卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/gansustv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 宁夏卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/ningxiastv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 青海卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/qinghaistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 海南卫视
http://120.210.193.151:8006/120000001002/XMThainanwshd/index.m3u8
#EXTINF:-1, group-title="地方卫视", 新疆卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/xinjiangstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 西藏卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/xizangstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 内蒙古卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/neimenggustv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 云南卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/yunnanstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 东南卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-dongnanstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 河南卫视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/henanstv/1.m3u8
#EXTINF:-1, group-title="其他", CETV-1
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jiaoyutv/1.m3u8
#EXTINF:-1, group-title="其他", CETV-4
http://120.210.193.151:8006/120000001002/XMTcetv-4/index.m3u8
#EXTINF:-1, group-title="地方卫视", 三沙卫视
http://120.210.193.151:8006/120000001002/XMTssws/index.m3u8
#EXTINF:-1, group-title="地方卫视", 厦门卫视
http://120.210.193.151:8006/120000001002/XMTxmws/index.m3u8
#EXTINF:-1, group-title="地方卫视", 兵团卫视
http://120.210.193.151:8006/120000001002/XMTbtws/index.m3u8
#EXTINF:-1, group-title="其他", CETV-2
http://120.210.193.151:8006/120000001002/XMTcetv-2/index.m3u8
#EXTINF:-1, group-title="其他", 黑莓动画
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/donghuawg/1.m3u8
#EXTINF:-1, group-title="其他", 古装剧场
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/guzhuangjc/1.m3u8
#EXTINF:-1, group-title="其他", 动作电影
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/dongzuody/1.m3u8
#EXTINF:-1, group-title="其他", 精品综合
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/mingxingdp/1.m3u8
#EXTINF:-1, group-title="其他", 金牌综艺
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/saishijx/1.m3u8
#EXTINF:-1, group-title="其他", 黑莓电影
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jdianying/1.m3u8
#EXTINF:-1, group-title="其他", 爱情喜剧
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/aiqingxj/1.m3u8
#EXTINF:-1, group-title="其他", 惊悚悬疑
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jingsongxy/1.m3u8
#EXTINF:-1, group-title="其他", 军事评论
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/junshipl/1.m3u8
#EXTINF:-1, group-title="其他", 军旅剧场
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/junlvjc/1.m3u8
#EXTINF:-1, group-title="其他", 热播精选
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/xiqumd/1.m3u8
#EXTINF:-1, group-title="其他", 家庭剧场
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jiatingjc/1.m3u8
#EXTINF:-1, group-title="其他", 精品大剧
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jdaju/1.m3u8
#EXTINF:-1, group-title="其他", 精品纪录
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jingpinjl/1.m3u8
#EXTINF:-1, group-title="其他", 精品体育
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jtiyu/1.m3u8
#EXTINF:-1, group-title="其他", 怡伴健康
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/ljiankangyouyue/1.m3u8
#EXTINF:-1, group-title="其他", 武搏世界
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/SD-1500k-576P-bokesen/1.m3u8
#EXTINF:-1, group-title="其他", 农业致富
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/nongyezf/1.m3u8
#EXTINF:-1, group-title="其他", 哒啵赛事
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/wmyx/1.m3u8
#EXTINF:-1, group-title="其他", 潮妈辣婆
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-1500k-720P-cmlapo/1.m3u8
#EXTINF:-1, group-title="其他", 金鹰卡通
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jinyingkaton/1.m3u8
#EXTINF:-1, group-title="其他", 炫动卡通
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/xuandongkaton/1.m3u8
#EXTINF:-1, group-title="其他", 卡酷少儿
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/kakukaton/1.m3u8
#EXTINF:-1, group-title="其他", 优漫卡通
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/youmankaton/1.m3u8
#EXTINF:-1, group-title="其他", 山东教育
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/shandongjy/1.m3u8
#EXTINF:-1, group-title="其他", 风尚购物
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/fengshanggw/1.m3u8
#EXTINF:-1, group-title="其他", 家有购物
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/SD-1500k-576P-jiayougw/1.m3u8
#EXTINF:-1, group-title="其他", 央广购物
http://120.210.193.151:8006/120000001002/XMTGW_yggw/index.m3u8
#EXTINF:-1, group-title="其他", 快乐购
http://120.210.193.151:8006/120000001002/XMTGW_klg/index.m3u8
#EXTINF:-1, group-title="其他", 足球频道
http://120.210.193.151:8006/120000001002/XMTzqpd/index.m3u8
#EXTINF:-1, group-title="其他", 好享购物
http://120.210.193.151:8006/120000001002/XMTGW_hxg/1.m3u8
#EXTINF:-1, group-title="其他", 优购物
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-yougw/1.m3u8
#EXTINF:-1, group-title="其他", 七彩戏剧
http://120.210.193.151:8006/120000001002/XMTqcxj/1.m3u8
#EXTINF:-1, group-title="其他", 动漫秀场
http://120.210.193.151:8006/120000001002/XMTdmxc/1.m3u8
#EXTINF:-1, group-title="其他", 金色频道
http://120.210.193.151:8006/120000001002/XMTjspd/1.m3u8
#EXTINF:-1, group-title="其他", 东方财经
http://120.210.193.151:8006/120000001002/XMTdfcj/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-1高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-cctv1/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-2高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-cctv2/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-3高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-cctv3/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-4高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-4/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-5
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-5/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-6高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-cctv6/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-7高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-7/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-8高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-cctv8/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-9高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-cctv9/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-10高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-10/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-11高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-11/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-12高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-12/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-13高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-13/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-14高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-14/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-15高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-15/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-16高清4M
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-cctv16/1.m3u8
#EXTINF:-1, group-title="CCTV", CCTV-17高清
http://120.210.193.151:8006/120000001002/XMTcctv-17hd/index.m3u8
#EXTINF:-1, group-title="CCTV", CCTV5+高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-cctv05plus/1.m3u8
#EXTINF:-1, group-title="其他", CGTN高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/cctv-9/1.m3u8
#EXTINF:-1, group-title="地方卫视", 安徽卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-anhuistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 湖南卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-hunanstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 东方卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-dongfangstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 北京卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-beijingstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 浙江卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-zhejiangstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 江苏卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-8M-1080P-jiangsustv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 天津卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/hdtianjinstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 山东卫视高清
http://120.210.193.151:8006/120000001002/XMTshandongwshd/index.m3u8
#EXTINF:-1, group-title="地方卫视", 辽宁卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-liaoningstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 深圳卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/hdshenzhenstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 江西卫视高清
http://120.210.193.151:8006/120000001002/XMTjiangxiwshd/index.m3u8
#EXTINF:-1, group-title="地方卫视", 贵州卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-guizhoustv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 广东卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/hdguangdongstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 湖北卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-hubeistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 河北卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-hebeistv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 重庆卫视高清
http://120.210.193.151:8006/120000001002/XMTchongqingwshd/index.m3u8
#EXTINF:-1, group-title="地方卫视", 四川卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-sichuanstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 甘肃卫视高清
http://120.210.193.151:8006/120000001002/XMTgswshd/index.m3u8
#EXTINF:-1, group-title="地方卫视", 东南卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-dongnanstv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 河南卫视高清
http://120.210.193.151:8006/120000001002/XMThenanwshd/index.m3u8
#EXTINF:-1, group-title="其他", CETV-1高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jiaoyutv/1.m3u8
#EXTINF:-1, group-title="地方卫视", 黑龙江卫视高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/hdheilongjiangstv/1.m3u8
#EXTINF:-1, group-title="其他", 金鹰卡通高清
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/jinyingkaton/1.m3u8
#EXTINF:-1, group-title="安徽本地", 安徽经济高清
http://120.210.193.151:8006/120000001002/XMTah_jjhd/index.m3u8
#EXTINF:-1, group-title="安徽本地", 安徽影视高清
http://120.210.193.151:8006/120000001002/XMTah_yshd/index.m3u8
#EXTINF:-1, group-title="安徽本地", 安徽科教高清
http://120.210.193.151:8006/120000001002/XMTah_kjhd/index.m3u8
#EXTINF:-1, group-title="安徽本地", 安徽综艺高清
http://120.210.193.151:8006/120000001002/XMTah_zyhd/index.m3u8
#EXTINF:-1, group-title="安徽本地", 安徽公共高清
http://120.210.193.151:8006/120000001002/XMTah_gghd/index.m3u8
#EXTINF:-1, group-title="安徽本地", 安徽国际
http://120.210.193.151:8006/120000001002/XMTahgj/index.m3u8
#EXTINF:-1, group-title="其他", 徽生活
http://120.210.193.151:8006/120000001002/GDhuish/index.m3u8
#EXTINF:-1, group-title="其他", 海豚生活
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/pltv-htsh/1.m3u8
#EXTINF:-1, group-title="安徽本地", 安徽导视
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/XMTahds/1.m3u8
#EXTINF:-1, group-title="安徽本地", 睛彩安徽
http://120.210.193.151:8006/120000001002/XMTjcah/index.m3u8
#EXTINF:-1, group-title="其他", 海豚健康
http://120.210.193.151:8006/120000001002/XMThtjk/1.m3u8
#EXTINF:-1, group-title="其他", 海豚影视
http://120.210.193.151:8006/120000001002/XMThtys/1.m3u8
#EXTINF:-1, group-title="其他", 海豚少儿
http://120.210.193.151:8006/120000001002/XMThtse/1.m3u8
#EXTINF:-1, group-title="其他", 超级综艺（测试）
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-NEWTV03/1.m3u8
#EXTINF:-1, group-title="其他", 超级体育（测试）
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-NEWTV05/1.m3u8
#EXTINF:-1, group-title="其他", 超级电影（测试）
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-NEWTV06/1.m3u8
#EXTINF:-1, group-title="其他", 超级电视剧（测试）
http://120.210.193.151:8006/120000001001/wlds:8080/ysten-business/live/HD-4000k-1080P-NEWTV08/1.m3u8
#EXTINF:-1, group-title="咪咕", 咪咕精彩足球频道
http://120.210.193.151:8006/120000001002/HD-8000k-1080P-miguaoyun1/1.m3u8
#EXTINF:-1, group-title="咪咕", 咪咕综合体育
http://120.210.193.151:8006/120000001002/HD-8000k-1080P-miguaoyun2/1.m3u8
#EXTINF:-1, group-title="咪咕", 咪咕冬奥-冰上
http://120.210.193.151:8006/120000001002/HD-8000k-1080P-migudongao4/1.m3u8
#EXTINF:-1, group-title="咪咕", 咪咕冬奥-雪上
http://120.210.193.151:8006/120000001002/HD-8000k-1080P-migudongao5/1.m3u8
#EXTINF:-1, group-title="咪咕", 咪咕冬奥-直击
http://120.210.193.151:8006/120000001002/HD-8000k-1080P-migudongao6/1.m3u8

**Comment by xuemeizhibo** [comment]
谢谢
